// Run: node tests/pdv1-sales.test.cjs. No network or external dependencies.
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=path.join(__dirname,'../orari-reparto-demo');
function element(){return {innerHTML:'',textContent:'',value:'',style:{},dataset:{},children:[],classList:{add(){},remove(){},toggle(){}},querySelector(){return null},querySelectorAll(){return[]},appendChild(){},insertAdjacentHTML(){},insertAdjacentElement(){},addEventListener(){},setAttribute(){},getAttribute(){return''},remove(){}}}
const nodes=Object.fromEntries(['app','nav','weeklabel','weekbar'].map(x=>[x,element()]));
const storage=new Map(),errors=[];
const context={console:{...console,error:(...a)=>errors.push(a.map(String).join(' '))},document:{querySelector:q=>nodes[q.slice(1)]||null,querySelectorAll:()=>[],getElementById:id=>nodes[id]||null,createElement:element,head:element(),body:element(),addEventListener(){}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},navigator:{},location:{href:'http://localhost/'},setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,clearInterval(){},alert(){},confirm:()=>false,prompt:()=>null,addEventListener(){},scrollTo(){},URL,Blob,fetch:async()=>{throw Error('Network disabled in tests')}};
context.window=context;vm.createContext(context);
for(const [,file] of fs.readFileSync(path.join(root,'index.html'),'utf8').matchAll(/<script src="([^?"]+)/g)){vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),context,{filename:file,timeout:20000})}
const run=code=>vm.runInContext(code,context,{timeout:20000});
assert.deepEqual(errors,[],'all modules initialize without an error');
let checks=0;
function check(label,code){try{assert.equal(run(code),true);checks++;console.log('PASS',label)}catch(e){console.error('FAIL',label);throw e}}
check('unknown skill levels remain unknown after normalization',`S.employees.every(e=>SALES_SKILLS.every(k=>normalizePdvState(S).employees.find(x=>x.name===e.name).skills[k]===null))`);
check('same closer must possess BOTH new skills',`!salesBoth({skills:{Scadenze:3,'Chiusura forno':null}})&&!salesBoth({skills:{Scadenze:1,'Chiusura forno':3}})&&salesBoth({skills:{Scadenze:2,'Chiusura forno':2}})`);
check('closure oven is not changed to a 06:00 start',`(()=>{const s={skill:'Chiusura forno',start:'14:30',end:'20:45'};pdv1349ApplyShiftRules(s);return s.start==='14:30'&&baseGridRequiredSkill(s,'g')==='Chiusura forno'&&pdv1349NormalizeSkill('Chiusura forno + Scadenze','g')==='Chiusura forno + Scadenze'})()`);
for(const from of ['2026-09-14','2026-09-21']){
  check('published daily totals match source '+from,`(()=>{week=new Date('${from}T12:00:00');const ds=edited(build()),actual=ds.map(d=>baseGridDayAssignments(d).reduce((n,x)=>n+shiftScheduledMinutes(x.shift),0));const expected=SALES_SOURCES['${from}'].daily.map(mins);if(JSON.stringify(actual)!==JSON.stringify(expected))console.log({actual,expected});return JSON.stringify(actual)===JSON.stringify(expected)})()`);
}
check('published overtime and training are preserved',`(()=>{week=new Date('2026-09-21T12:00:00');const ds=edited(build());return ds[5].g.find(s=>s.name.trim()==='Antonio').end==='14:00'&&ds[3].g.find(s=>s.name==='Maia').excludeFromDepartmentHours&&ds[2].g.find(s=>s.name==='Maia').start==='15:00'})()`);
check('import archives legacy edits once and preserves subsequent changes',`(()=>{const old=cloneJson(S);delete S.salesImportVersion;S.edits={'2026-09-22-g-0':{deleted:true},'2026-10-05-g-0':{name:'Keep'}};salesMigratePublishedEdits();const archived=S.salesImportArchive.edits['2026-09-22-g-0']?.deleted;S.edits['2026-09-22-g-0']={end:'12:45'};salesMigratePublishedEdits();const ok=archived&&S.edits['2026-09-22-g-0'].end==='12:45'&&S.edits['2026-10-05-g-0'].name==='Keep';S=old;return ok})()`);
check('configured slots match Monday through Saturday and Friday is pending',`(()=>{return [0,5].every(i=>salesSlots(i).find(s=>s.skill==='Servizio').start==='08:00')&&[1,2,3].every(i=>salesSlots(i).find(s=>s.skill==='Servizio').start==='09:30')&&!salesSlots(4).some(s=>s.skill==='Servizio')&&salesSlots(2).find(s=>s.skill==='Ordini').start==='07:00'&&salesSlots(2).at(-1).start==='14:30'})()`);
check('future generation keeps unknown roles uncovered',`(()=>{week=new Date('2026-09-28T12:00:00');const ds=edited(build());return ds[0].g.find(s=>s.salesRequired===SALES_SKILLS[0]).name==='SCOPERTO'&&ds[0].g.some(s=>s.salesRequired==='Chiusura forno + Scadenze'&&s.name==='SCOPERTO')&&ds[4].salesFridayPending})()`);
check('qualified second closer may cover BOTH while first only has Scadenze',`(()=>{const old=cloneJson(S);S.employees=Array.from({length:6},(_,i)=>({name:'Test'+i,dept:'gastronomia',hours:40,skills:{Forno:i===0?3:0,Ordini:i===2?3:0,Servizio:3,[SALES_SKILLS[0]]:i===1?3:0,Scadenze:i>=4?3:0,'Chiusura forno':i===5?3:0}}));S.leaves=[];S.absences=[];S.sicknessSpans=[];S.availabilityBlocks=[];const out=[{date:new Date('2026-09-28T12:00:00'),g:[],c:[],cr:null}];salesAssignDay(out,0,{});const slots=out[0].g;const ok=slots.length===6&&new Set(slots.map(s=>s.name)).size===6&&slots.at(-2).name==='Test4'&&slots.at(-1).name==='Test5';S=old;return ok})()`);
check('skills on different closers never pass team audit',`(()=>{const old=cloneJson(S);S.employees=[{name:'A',hours:40,skills:{Servizio:3,Scadenze:3,'Chiusura forno':0}},{name:'B',hours:40,skills:{Servizio:3,Scadenze:0,'Chiusura forno':3}}];S.leaves=[];S.absences=[];S.sicknessSpans=[];S.availabilityBlocks=[];const ds=[{date:new Date('2026-09-28T12:00:00'),g:[{name:'A',start:'13:30',end:'20:45',skill:'Chiusura'},{name:'B',start:'14:30',end:'20:45',skill:'Chiusura'}],c:[],cr:null}];salesAudit(ds);const ok=ds.salesAudit.some(x=>x.text.includes('uno stesso addetto'));S=old;return ok})()`);
check('PDV2 keeps the preceding generator and no sales templates',`(()=>{const old=cloneJson(pdvDb),state=cloneJson(S);pdvDb.pdvs.push({id:'PDV_002',state:cloneJson(S)});pdvDb.activeId='PDV_002';week=new Date('2026-09-28T12:00:00');const ds=build(),ok=ds.every(d=>!d.salesTemplate&&!d.salesPublished);pdvDb=old;S=state;return ok})()`);
console.log(checks+' checks passed');
