const names={
'Gastronomia':['Prosciutto cotto alta qualità','Prosciutto crudo nazionale','Prosciutto crudo toscano','Mortadella Bologna IGP','Salame toscano','Salame Milano','Finocchiona IGP','Soppressata toscana','Bresaola punta anca','Speck Alto Adige','Pancetta arrotolata','Pancetta tesa','Coppa stagionata','Porchetta arrosto','Tacchino arrosto','Pollo arrosto affettato','Roast beef','Vitello tonnato','Insalata russa','Insalata capricciosa','Mozzarella fiordilatte','Mozzarella bufala','Burrata','Stracciatella','Ricotta vaccina','Ricotta pecora','Scamorza bianca','Scamorza affumicata','Provolone dolce','Provolone piccante','Parmigiano Reggiano 24m','Grana Padano','Pecorino toscano fresco','Pecorino toscano stagionato','Pecorino romano','Gorgonzola dolce','Gorgonzola piccante','Taleggio','Fontina','Asiago','Emmental','Brie','Camembert','Mascarpone','Formaggio spalmabile','Olive verdi condite','Olive nere','Carciofini sottolio','Pomodori secchi','Antipasto misto'],
'Forneria':['Filone toscano','Baguette','Ciabatta','Schiacciata olio','Schiacciata croccante','Pane integrale','Pane ai cereali','Pane di segale','Pane senza sale','Pane pugliese','Pane casereccio','Pane di semola','Pane di grano duro','Pane multicereali','Pane noci','Pane olive','Pane curcuma','Pane farro','Panini rosette','Panini all’olio','Panini latte','Panini hamburger','Panini hot dog','Focaccia pomodoro','Focaccia cipolla','Focaccia olive','Pizza margherita','Pizza rossa','Pizza farcita','Pizzette','Cornetto vuoto','Cornetto crema','Cornetto cioccolato','Cornetto integrale','Treccia crema','Saccottino cioccolato','Krapfen','Sfoglia mela','Muffin','Crostata albicocca','Crostata cioccolato','Torta della nonna','Cantucci','Biscotti frollini','Grissini','Crackers forno','Farina tipo 0','Farina integrale','Lievito fresco','Base pizza'],
'Rosticceria':['Pollo arrosto','Cosce pollo arrosto','Patate arrosto','Lasagne','Cannelloni ricotta spinaci','Parmigiana melanzane','Arancini','Crocchette patate','Verdure grigliate','Polpette al sugo'],
'Carni':['Bistecca fiorentina','Costata bovino','Tagliata bovino','Roast beef bovino','Spezzatino bovino','Macinato bovino','Hamburger bovino','Bollito bovino','Ossobuco bovino','Fegato bovino','Petto pollo','Cosce pollo','Sovracosce pollo','Ali pollo','Pollo intero','Fesa tacchino','Coscia tacchino','Coniglio intero','Lombo suino','Arista suino','Braciole suino','Costine suino','Salsiccia toscana','Macinato suino','Pancetta fresca','Filetto suino','Coppa fresca','Stinco suino','Agnello costolette','Agnello coscio','Agnello spezzatino','Vitello fettine','Vitello arrosto','Vitello spezzatino','Polpette miste','Hamburger pollo','Spiedini misti','Involtini carne','Preparato ragù','Preparato polpettone'],
'Pesce':['Orata','Branzino','Salmone trancio','Tonno trancio','Merluzzo filetto','Seppie','Calamari','Gamberi','Cozze','Vongole']};
const holidays=['2026-08-15','2026-11-01','2026-12-08','2026-12-25','2026-12-26'];
let dept='Gastronomia', mode='exceptions', copyIndex=0;
const key='ordini-freschi-demo-v1';
let state=JSON.parse(localStorage.getItem(key)||'null')||{};
function build(){Object.entries(names).forEach(([d,arr])=>arr.forEach((n,i)=>{const id=d+'-'+i;if(!state[id]) state[id]={qty:(i%5===0?2:1),stock:'OK',promo:i%13===0,risk:i%17===0,code:String(100000+i+(Object.keys(names).indexOf(d)*1000)).padStart(6,'0')};}));save()}
function save(){localStorage.setItem(key,JSON.stringify(state))}
function todayInfo(){const d=new Date();document.querySelector('#today').textContent=d.toLocaleDateString('it-IT',{weekday:'long',day:'numeric',month:'long',year:'numeric'});const iso=d.toISOString().slice(0,10);document.querySelector('#calendarBanner').textContent=holidays.includes(iso)?'Oggi è festivo: proposta aumentata e controllo promosso.':'Calendario attivo: prossima festività 15 agosto 2026. Le promo e i prefestivi restano separati nello storico.'}
function renderNav(){const n=document.querySelector('#departments');n.innerHTML='';Object.keys(names).forEach(d=>{const b=document.createElement('button');b.className='dept'+(d===dept?' active':'');b.textContent=`${d} (${names[d].length})`;b.onclick=()=>{dept=d;render()};n.appendChild(b)})}
function adjustedQty(s){const t=document.querySelector('#dayType').value;const m={Debole:.8,Forte:1.25,Prefestivo:1.35,Festivo:1.5,'Post-festivo':.75,Normale:1}[t];return Math.max(0,Math.round(s.qty*m+(s.promo?1:0)+(s.stock==='ZERO'?1:s.stock==='ALTA'?-1:0)))}
function visible(){return names[dept].map((name,i)=>({name,id:dept+'-'+i,s:state[dept+'-'+i]})).filter(x=>mode==='all'||x.s.promo||x.s.risk||x.s.stock!=='OK')}
function render(){renderNav();const v=visible();document.querySelector('#countItems').textContent=`${names[dept].length} articoli`;document.querySelector('#countPromo').textContent=`${names[dept].filter((_,i)=>state[dept+'-'+i].promo).length} promo`;document.querySelector('#countCheck').textContent=`${v.length} da controllare`;const list=document.querySelector('#list');list.innerHTML='';if(!v.length){list.innerHTML='<div class="empty">Nessuna eccezione. L’ordine base è pronto.</div>';return}v.forEach(x=>{const q=adjustedQty(x.s);const el=document.createElement('article');el.className='item';el.innerHTML=`<div><h3>${x.name}</h3><div class='meta'><span>Codice ${x.s.code}</span>${x.s.promo?"<span class='promo'>PROMO</span>":''}${x.s.risk?"<span class='risk'>CONTROLLO</span>":''}</div><div class='stock'>${['ZERO','BASSA','OK','ALTA'].map(z=>`<button data-stock='${z}' class='${x.s.stock===z?'active':''}'>${z}</button>`).join('')}</div></div><div class='qty'><button data-minus>−</button><strong>${q}</strong><button data-plus>+</button></div>`;el.querySelector('[data-minus]').onclick=()=>{x.s.qty=Math.max(0,x.s.qty-1);save();render()};el.querySelector('[data-plus]').onclick=()=>{x.s.qty++;save();render()};el.querySelectorAll('[data-stock]').forEach(b=>b.onclick=()=>{x.s.stock=b.dataset.stock;save();render()});list.appendChild(el)})}
function copyList(){return names[dept].map((name,i)=>({name,s:state[dept+'-'+i]})).map(x=>({...x,qty:adjustedQty(x.s)})).filter(x=>x.qty>0)}
function showCopy(){const arr=copyList();if(!arr.length)return;copyIndex=Math.max(0,Math.min(copyIndex,arr.length-1));const x=arr[copyIndex];document.querySelector('#copyCard').innerHTML=`<div class='copyCard'><div>${copyIndex+1} di ${arr.length}</div><h2>${x.name}</h2><div class='code'>Codice ${x.s.code}</div><div class='bigQty'>${x.qty}</div><div>${x.s.promo?'PROMO ATTIVA':''}</div></div>`}
document.querySelector('#exceptionsBtn').onclick=()=>{mode='exceptions';render()};document.querySelector('#allBtn').onclick=()=>{mode='all';render()};document.querySelector('#copyBtn').onclick=()=>{copyIndex=0;showCopy();document.querySelector('#copyDialog').showModal()};document.querySelector('#nextCopy').onclick=()=>{copyIndex++;if(copyIndex>=copyList().length)document.querySelector('#copyDialog').close();else showCopy()};document.querySelector('#prevCopy').onclick=()=>{copyIndex--;showCopy()};document.querySelector('#skipCopy').onclick=()=>{copyIndex++;showCopy()};document.querySelector('#dayType').onchange=render;document.querySelector('#resetBtn').onclick=()=>{localStorage.removeItem(key);location.reload()};build();todayInfo();render();